version: '3.8'
services:
  django_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8001"
    env_file:
      - .env
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
    postgres_data:
